### ISSUE TITLE
Database hosting

### ISSUE THREAD

**Issue by justinwash** [Trifectuh/PerpetualShred#12]
decide how to go about database hosting.  Working with LocalDB at the moment. Should be simple to migrate to another platform/azure/pi/cloud storage once we decide which option will work best/be cheapest.

**Comment by afterparty** [comment]
Here's an option https://somee.com/default.aspx
As well as azure
or my raspberry pi, but that will be harder to keep up all the time.

**Comment by justinwash** [comment]
pricing is decent. wonder how it compares to the pay-as-you-go model azure uses. i think I was averaging $12 a month or so hosting the Outsidr testing site but I'll have to check. Could get expensive fast if it gets any traction.

**Comment by afterparty** [comment]
I think because I have a msdn account through my work I get a bunch of free credits on azure. I'll have to check that out.

**Comment by justinwash** [comment]
Yeah may be look into that. It looks like actually running the crawler and site, the vid and user DBs all-in-one will be cheapest and easiest to set up there. but I'll keep looking. can always get deploybot set up with another host if we find one that works better. aubs suggested hostgator since that what she uses for her blogs. It's awful.

**Comment by justinwash** [comment]
closing, since we're live now at www.perpetualshred.com
