### ISSUE TITLE
Missing core feature - database

### ISSUE THREAD

**Issue by justinwash** [Trifectuh/PerpetualShred#2]
To hold video urls, information about them such as title, origin, synopsis, etc

**Comment by afterparty** [comment]
Yea, we either need a cloud db or a server. Not sure which is more practical. I could maybe use my pi?

**Comment by justinwash** [comment]
opted for cloud db for now, since were not hosting the videos themselves (yet?) can always convert later if it doesnt do everything we need it to. Gonna close this issue for now and make some more specific ones.
